name: todo-counter
author: Dimitar Rusev
description: Counts the TODOs in your code
inputs:
  include-files:
    description: Regular expression of files to include when checking for TODOs. Will not respect .gitignore
    required: false
  exclude-files:
    description: Regular expression of files to exclude when checking for TODOs
    required: false
  todo-regex:
    description: Regular expression of strings to search for
    required: false
    default: 'TODO:'
outputs:
  count:
    description: Count of TODOs
runs:
  using: node20
  main: 'dist/index.js'
branding:
  icon: file-text
  color: purple
