on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Count TODOs
        id: this
        uses: mitiko/todo-counter@5679c21d046528c9c827cab440bf76765730c3ad
        with:
          todo-regex: 'TODO:'
          include-files: '\.json$'
      - name: Print count
        run: echo "The count was ${{ steps.this.outputs.count }}"
