on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Count TODOs
        id: this
        uses: mitiko/todo-counter@main
        with:
          todo-regex: 'TODO:'
          exclude-files: '^(\.git\/|dist\/)'
      - name: Print count
        run: echo "The count was ${{ steps.this.outputs.count }}"
