on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Run Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Count TODOs
        id: this
        uses: mitiko/todo-counter@test
        with:
          todo-regex: 'TODO:'
          exclude-files: '^\.git'
      - name: Print count
        run: echo "The count was ${{ steps.this.outputs.count }}"
